version: "3.4"

services:
  sportex:
    image: sportex
    build: .
    environment:
      NODE_ENV: production
      REDIS_HOST: redis://db:6379
    ports:
      - 5000:5000
    redis:
      container_name: redis-cache
      image: redis
      ports:
        - "6379:6379"
